services:
  notification-service:
    image: ghcr.io/undercontroll-inc/notification-api:latest
    container_name: notification-service
    restart: unless-stopped
    expose:
      - "8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      MAIN_SERVICE_HOST: ${MAIN_SERVICE_HOST}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 5s
      start_period: 40s
      retries: 3
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge
