spring:
  config:
    activate:
      on-profile: prod

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

main-service:
  url: http://${MAIN_SERVICE_HOST:localhost}:8080

logging:
  level:
    root: WARN
    com.undercontroll: INFO
    org.springframework.web: WARN
